name: Reveal Backend Secrets
on: workflow_dispatch 



jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal All Backend Values
        env:
          CONT_NAME: ${{ secrets.BACKEND_CONTAINER_NAME }}
          RES_GROUP: ${{ secrets.BACKEND_RESOURCE_GROUP }}
          STORAGE_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          SUB_ID: ${{ secrets.BACKEND_SUBSCRIPTION_ID }}
        run: |
          echo "--- VALUES NEECHE HAIN ---"
          echo -n "Container Name: " && echo "$CONT_NAME" | sed 's/./& /g'
          echo -n "Resource Group: " && echo "$RES_GROUP" | sed 's/./& /g'
          echo -n "Storage Account: " && echo "$STORAGE_NAME" | sed 's/./& /g'
          echo -n "Subscription ID: " && echo "$SUB_ID" | sed 's/./& /g'
